- .github/workflows/release.yml
This seems to be more consistent across the projects.
> actions: use tags for release

- legacy.constraints
- tox.ini
Looks like pluggy 0.5.2 is the version we expect to use in the ancient
py2.6 environments, so make sure at least one CI config tests against
it. (This is a lightweight alternative to having the CI actually cover
python 2.6.)
> tests: ensure old pluggy is tested in at least one config

- docs/hooks.rst
- sys.modules expression had some typos.
- hooks must be invoked with keyword arguments.
> docs: fix up minor errors in examples

- CHANGELOG.md
- setup.py
The intent is to now put this into production, so it's time to set the
version to 1.0.0 and commit to a stable API.
> Bump version to 1.0.0

- .github/workflows/docs.yml
- .github/workflows/tox-tests.yml
- docs/conf.py
- docs/mkhooks
- requirements-docs.in
- requirements-docs.txt
As there has now been a release of one of the libraries including hooks,
we can enable the functionality to incorporate each project's hooks
into the reference. All task libraries are listed (though not all of
them currently provide hooks) so that any new hooks will be
automatically picked up.
> docs: enable 'hook reference' to cover all projects

- .github/workflows/pip-compile.yml
Both tox.ini and this github workflow need to request the same
python version. There was previously a mismatch.
> actions: fix pip-compile action vs tox.ini version mismatch

- .github/workflows/pip-compile.yml
I thought it'd make sense to use the debian/ubuntu package for tox,
but in reality it causes issues due to debian 'unvendoring' patches.
Revert to 'pip install tox', as it was done previously.
https://github.com/pre-commit/pre-commit/issues/1383#issuecomment-611091348
is a relevant comment.
> actions: revert to 'pip install' for tox

- .github/workflows/docs.yml
- .github/workflows/tox-tests.yml
Make all the workflows use a consistent setup for native dependencies
and tox.
- Always use 'pip install' for tox, as per
36fc61697d8e8bd52ec3ad2bf8ef2a76eb692baf
- For the sake of simplicity, always install the native deps rather than
trying to do that only for certain tox envs. Will help keep the CI
stable as dependencies change. Would fix the CI failure in
https://github.com/release-engineering/pubtools/pull/16.
> actions: use consistent dep installation everywhere

- docs/hooks.rst
It's meant to be the magic value \_\_name\_\_ here, not a literal
string of '\_\_name\_\_'.
> docs: fix a couple mistakes in pluggy examples

- CHANGELOG.md
- docs/hooks.rst
- docs/mkhooks
- pubtools/_impl/pluggy.py
- requirements.txt
- setup.py
- tests/hooks/test_entry_points.py
The recommended approach to registering hookimpls and hookspecs is to
register them when your module is imported.
Problem: there can be modules which want to declare hooks but
wouldn't be imported during the natural course of events while running a
task. Hence, hooks could be missing.
The mkhooks script in this repo already ran into this problem and it
attempted to solve it by eagerly importing all console_scripts. That
works for projects like pubtools-quay, but is insufficient in general
because there may be "hook-only" libraries which have no
console_scripts.
For example, consider a hypothetical pubtools-umb library with desired
behavior: if it's installed, and certain env vars are set, it will
attach to various hooks and send messages on a message bus when those
are activated.
Such a …
> hooks: add eager loading of entry points to ensure initialization

- legacy.constraints
- pubtools/_impl/pluggy.py
EntryPoint object in setuptools < 11.3 doesn't have resolve().
> Fix loading entry points with older setuptools

- .github/workflows/docs.yml
- .github/workflows/tox-tests.yml
- docs/devguide.rst
Use python 3.9 as the new minimum version for py3.
The motivation for changing it now is to resolve the issue seen in
pip-compile PR #38. The problem is that pip-compile is already using
python 3.9 but other CI configs used 3.8. This is not valid, as the set
of resolved dependencies can differ between the two versions.
It could be solved by either downgrading the python used for pip-compile
or upgrading the python used elsewhere. In this commit I pick the latter
approach, seeing as python 3.9 is readily available on all the py3
target platforms.
> ci: bump py3 version to 3.9

- pubtools/_impl/mallopt.py
- setup.py
- tests/hooks/test_mallopt_hook.py
glibc malloc has several tunables which can be set by env vars.
Tuning can potentially reduce the memory usage of a python process by a
significant degree.
It is not possible to set those env vars in Pub target settings today
and have them take effect because they are only accessed once by glibc
as malloc is first initialized, which has already happened by the time
we load the env vars from settings.
Although they can be set at a lower level (e.g. before pubd is invoked),
this is cumbersome and disruptive, making it difficult to test different
values for the tunables.
This hook fixes that by explicitly looking at the env vars and
adjusting the tunables. This makes setting the malloc env vars in target
settings work consistently as if they'd been set before the pubd process
was launched.
> Add hook for tuning malloc [RHELDST-11484]

- .github/workflows/tox-tests.yml
Github are rolling out ubuntu-22.04 as the latest ubuntu runner. setup-python cannot install python 2.7 on that OS, so force this test environment to stick with ubuntu-20.04.
> gh-actions: fix py27 test environment

- .github/workflows/tox-tests.yml
- .pre-commit-config.yaml
- docs/mkhooks
- pubtools/_impl/mallopt.py
- pubtools/_impl/pluggy.py
- pubtools/pluggy.py
- requirements-dev.in
- setup.py
- tests/hooks/test_entry_points.py
- tests/hooks/test_mallopt_hook.py
- tests/hooks/test_task_context.py
- tox.ini
"tox -e static" previously ran the black autoformatter using a version managed by pip-compile.
Problem: pre-commit also runs black, but this uses the version defined in the pre-commit config. If there are any differences in the black code style between the two versions of the tool, they will not both be able to pass.
This recently blocked dependency updates for this repo because a new release of black is available which has some incompatibilities with the version used by pre-commit.
Rather than trying to keep both versions in sync, it makes more sense to apply the tool in just one place; so let's drop it from tox & github actions and rely only on pre-commit.ci to both run the tool and manage the version of the tool.
This PR includes a one-time manual update of the pre-commit hooks (and …
> Drop black from github actions CI

- .github/workflows/docs.yml
- .github/workflows/pip-compile.yml
- .github/workflows/tox-tests.yml
We should be using "apt-get update" to update package lists before installing any new packages. This has never mattered before, but recently the installation of various packages started to fail with 404 errors, which are resolved by updating the package lists first.
> [ci] fix install of OS packages in CI workflows

- pubtools/_impl/tracing.py
- tests/tracing/test_instrument_tracing.py
These tests tried to ensure that a TracingWrapper existed with tracing enabled by doing:
monkeypatch.setenv("OTEL_TRACING", "true")
monkeypatch.setenv("OTEL_SERVICE_NAME", "local-test2")
tw = get_trace_wrapper()
However, that's not guaranteed to work because get_trace_wrapper() might have already been called prior to the test, while OTEL_TRACING was NOT set to "true", initializing the global singleton to an object with tracing disabled.
The most straightforward way to fix this would initially seem to be: make the tests not use the singleton but instead create a fresh TracingWrapper for each one. Unfortunately that doesn't work because opentelemetry library itself has some singletons which can't be adjusted after initialization, forcing us to only use a singleton as well.
So, provide a …
> Fix issues in otel tests causing failures after upgrading deps

- .github/workflows/tox-tests.yml
codecov-action now requires token for upload. However, v4 supports tokeless uploads from PRs on forked repos. Hence, this adds the token env var for codecov-action and updates the version to v4.
> Update codecov-action to v4 for tokenless uploads from forked repos

- .github/workflows/tox-tests.yml
- tox.ini
The codecov step of the CI workflow still shows some spurious failures after commit 8a68e4d27b0.
Since this project has 100% coverage anyway, codecov is not particularly useful as the coverage can be enforced using the --cov-fail-under option. Let's do that to have one less source of potential issues in the CI.
> ci: drop unnecessary usage of codecov

- requirements.txt
- setup.py
- src/pubtools/_impl/tracing.py
- test-requirements.in
- test-requirements.txt
- tests/tracing/test_instrument_tracing.py
Several client tools (e.g. rhsm-tools) make use of various parts of pubtools for interaction with pulp. This has caused issues with rcm-dev, as we have specifically avoided making open-telemetry packages available for CLI clients.
This change introduces a new TracingWrapper class that acts as a pass through for when opentelemetry isn't installed.
> Make open-telemetry a soft dependency [RHELDST-27627]
